print("XII STANDARD MARK SHEET")
print("Student name S R AMIRTHA")
print("TAMIL :189")
print("ENGLISH :177")
print("MATHAMENTICS :152")
print("PHYSICS :177")
print("CHEMISTRY :181")
print("COMPUTER SCIENCE : 162")
print("***TOTAL MARKS*** 1020")
